  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
        
    redis:
      image: redis
      ports:
        - "6379:6379"
       
    web:
      build: .
      command: gunicorn djprog.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
        - redis
    
    worker:
      build: .
      command: celery -A tasks worker --pool=solo -l info
      volumes:
        - .:/code
      links:
        - redis
      depends_on:
        - db
        - redis
        
    nginx:
      build: ./nginx
      volumes:
        - .:/code
      ports:
        - 1337:80
      depends_on:
        - web
